# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  Major: '3'
  Minor: '0'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: pack
    configuration: 'release'
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Build.BuildId)'
    verbosityPack: 'minimal'
    packDirectory: '$(build.artifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
