# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2017-win2016'

variables:
  Version: '3.0.$(Build.BuildId)'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '-c Release'

  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\$(BuildConfiguration)\*Test*.dll
        **\$(BuildConfiguration)\**\*Test*.dll
        !**\*Microsoft.VisualStudio.TestPlatform*
        !**\obj\**
      codeCoverageEnabled: true

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      configuration: 'release'
      versioningScheme: byEnvVar
      versionEnvVar: 'Version'
      verbosityPack: 'minimal'
      projects: 'src/**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: push
      nuGetFeedType: 'internal'
      publishVstsFeed: 'BioEngine'
      versioningScheme: byEnvVar
      versionEnvVar: 'Version'
