pool:
  vmImage: vs2017-win2016
variables:
  Version: 3.0.$(Build.BuildId)
steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '-c Release'
  - task: VSTest@2
    inputs:
      testSelector: testAssemblies
      testAssemblyVer2: |
        **\Release\*Tests*.dll
        **\Release\**\*Tests*.dll
        !**\*Microsoft.VisualStudio.TestPlatform*
        !**\obj\**
      codeCoverageEnabled: true
  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      configuration: Release
      versioningScheme: byEnvVar
      versionEnvVar: Version
      verbosityPack: minimal
      projects: src/**/*.csproj
  - task: DotNetCoreCLI@2
    inputs:
      command: push
      nuGetFeedType: internal
      publishVstsFeed: BioEngine
      versioningScheme: byEnvVar
      versionEnvVar: Version
